### ISSUE TITLE
A brief list of various quirks and kinks.

### ISSUE THREAD

**Issue by II-H** [jcs/spoonfish#1]
First off, thank you for this. I was intrigued by your description of sdorfehs in your Q&A last year [^1] and had not found a suitable alternative prior to spoonfish.

I understand this this project is essentially a personal solution that works well enough for you. That's all that matters in truth. Please don't feel obliged to remedy any issues that I've listed. Some of them may be a result of ignorance on my part or an issue with Hammerspoon on my machine (2017 13in MBP running Big Sur). What I'm truly interested is an explanation or directive for these problems that I'm having rather than solutions in the form of labor on your part (unless you feel interested in doing so)...I'm functionally illiterate in regard to programming but Lua doesn't intimidate me.

1. I have to start spoonfish manually from the Hammerspoon console for some reason. My `init.lua` file contains exactly what you've provided in the readme. However, spoonfish does not "watch" any open windows when Hammerspoon first runs or when I manually reload the config from the menu bar. The only window that is watched by spoonfish is iTerm. By manually starting spoon fish, I mean that I have to open the Hammerspoon console and enter `spoonfish.start()`.

2. I have a problem with removing frames. `ctrl-R` is *seeming* ineffective. What does happen though, is that the window that is displayed in the frame that is supposed to be removed becomes "unwatched" in practice. Meaning that it is no long able to be manipulated by spoonfish. This only affects whichever window is on the screen when the frame is supposed to be removed [^2]. If this window is minimized, the frame's border/shadow will remain on the screen until the Hammerspoon configuration is reloaded (which presents a functional inconvenience in relation to my first problem). Below is reproduction of what appears in the Hammerspoon console when `ctrl-R` is keyed.

    ```
    2023-01-27 10:44:03: 10:44:03 
    ERROR:   LuaSkin: hs.eventtap callback error: /Users/user/.hammerspoon/spoonfish/windows.lua:31: attempt to concatenate a nil value (field 'title')
    stack traceback:
	/Users/user/.hammerspoon/spoonfish/windows.lua:31: in function 'spoonfish/init.window_reframe'
	/Users/user/.hammerspoon/spoonfish/frames.lua:359: in function 'spoonfish/init.frame_remove'
	/Users/user/.hammerspoon/spoonfish/init.lua:236: in function </Users/user/.hammerspoon/spoonfish/init.lua:117>
    ```

4. Is there any functional difference between `ctrl-n` and `ctrl-SPACE`?

Again, thanks for this. Spoonfish was the last piece of software that I was genuinely excited to use. 

Take care.

[^1]: Please do another, if you're able to, somehow.
[^2]: I just found out that windows can be cycled through irrespective of what frame they were last viewed. In other words, windows are not beholden to the frame that they were last displayed. This is very smart and convenient. Thanks.

**Comment by jcs** [comment]
Yes, removing frames is not working properly because it does not resize the other frames around it.  I just haven't implemented that because the logic is kinda lengthy.

I fixed the README, but you need to define `spoonfish.apps_to_watch` before calling `spoonfish.start`.  I also added an `apps_to_ignore` setting if you want to watch all apps by default (`spoonfish.apps_to_watch = { "" }`) and then just ignore some (`spoonfish.apps_to_ignore = { "^Finder" }`).

I haven't really been using this to watch all apps, just iTerm windows and a few maximized apps on different spaces like Firefox and such.  Personally I'm not a fan of putting all macOS windows in frames because most aren't designed to be in small windows, so you end up having do a lot of frame shuffling to be able to see content in apps properly.

Anyway, this is just kind of an experiment to see how it goes.  I've already found that Hammerspoon's window/app watching is not very reliable, so it will just randomly stop seeing new or existing windows from apps like Firefox.  I haven't figured out why yet.

**Comment by II-H** [comment]
I appreciate your response. 

> I haven't really been using this to watch all apps, just iTerm windows and a few maximized apps on different spaces like Firefox and such. Personally I'm not a fan of putting all macOS windows in frames because most aren't designed to be in small windows, so you end up having do a lot of frame shuffling to be able to see content in apps properly.

This approach solves my second point. I'm good. Thanks for your help.
